<?php
/**
 * AuditEntry value object.
 *
 * Immutable. Generated internally by the repository; never constructed from
 * user-supplied input. Satisfies contract §Public Common API: "AuditEntry is
 * generated by the repository from actor->ID, UTC instant, request ID, reason
 * and before/after field snapshots. Input cannot supply or replace audit entries."
 *
 * @package MF\VeLog\Common\Storage
 */

namespace MF\VeLog\Common\Storage;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Represents one immutable audit event appended to a record's history.
 *
 * @since 0.2.0
 */
final class AuditEntry {

	/**
	 * Actor WordPress user ID.
	 *
	 * @var int
	 */
	private int $actor_id;

	/**
	 * UTC ISO-8601 timestamp of the mutation.
	 *
	 * @var string
	 */
	private string $at_utc;

	/**
	 * Caller-generated idempotency UUID (stored for reconciliation; not
	 * returned to HTTP callers as a raw value).
	 *
	 * @var string
	 */
	private string $request_id;

	/**
	 * Human-readable mutation reason (may be empty string).
	 *
	 * @var string
	 */
	private string $reason;

	/**
	 * Operation type: 'create' or 'save'.
	 *
	 * @var string
	 */
	private string $op;

	/**
	 * Scalar snapshot of fields before the mutation (empty for create).
	 *
	 * @var array<string, mixed>
	 */
	private array $before;

	/**
	 * Scalar snapshot of fields after the mutation.
	 *
	 * @var array<string, mixed>
	 */
	private array $after;

	/**
	 * Private constructor — use AuditEntry::for_create() or AuditEntry::for_save().
	 *
	 * @param int                  $actor_id   WP user ID.
	 * @param string               $at_utc     UTC ISO-8601.
	 * @param string               $request_id Caller UUID.
	 * @param string               $reason     Mutation reason.
	 * @param string               $op         'create' or 'save'.
	 * @param array<string, mixed> $before     Fields before mutation.
	 * @param array<string, mixed> $after      Fields after mutation.
	 */
	private function __construct(
		int $actor_id,
		string $at_utc,
		string $request_id,
		string $reason,
		string $op,
		array $before,
		array $after
	) {
		$this->actor_id   = $actor_id;
		$this->at_utc     = $at_utc;
		$this->request_id = $request_id;
		$this->reason     = $reason;
		$this->op         = $op;
		$this->before     = $before;
		$this->after      = $after;
	}

	/**
	 * Creates an audit entry for a record creation event.
	 *
	 * Must only be called from trusted repository code with server-generated
	 * timestamp and validated actor.
	 *
	 * @param \WP_User             $actor      Authenticated actor.
	 * @param string               $request_id Caller UUID.
	 * @param array<string, mixed> $fields     Fields written.
	 * @return self
	 */
	public static function for_create( \WP_User $actor, string $request_id, array $fields ): self {
		return new self(
			(int) $actor->ID,
			gmdate( 'Y-m-d\TH:i:s\Z' ),
			$request_id,
			'',
			'create',
			array(),
			$fields
		);
	}

	/**
	 * Creates an audit entry for a record save (update) event.
	 *
	 * Must only be called from trusted repository code with server-generated
	 * timestamp and validated actor.
	 *
	 * @param \WP_User             $actor      Authenticated actor.
	 * @param string               $request_id Caller UUID.
	 * @param string               $reason     Human-readable reason.
	 * @param array<string, mixed> $before     Field values before mutation.
	 * @param array<string, mixed> $after      Field values after mutation.
	 * @return self
	 */
	public static function for_save(
		\WP_User $actor,
		string $request_id,
		string $reason,
		array $before,
		array $after
	): self {
		return new self(
			(int) $actor->ID,
			gmdate( 'Y-m-d\TH:i:s\Z' ),
			$request_id,
			$reason,
			'save',
			$before,
			$after
		);
	}

	/**
	 * Returns a serializable array representation of this audit entry.
	 *
	 * This is the form stored inside the `_mf_velog_record` meta envelope.
	 * Request ID is hashed before storage so it is not directly exposed.
	 *
	 * @return array<string, mixed>
	 */
	public function to_array(): array {
		return array(
			'actor_id'          => $this->actor_id,
			'at_utc'            => $this->at_utc,
			'request_id_sha256' => hash( 'sha256', $this->request_id ),
			'reason'            => $this->reason,
			'op'                => $this->op,
			'before'            => $this->before,
			'after'             => $this->after,
		);
	}

	/**
	 * Returns actor ID.
	 *
	 * @return int
	 */
	public function get_actor_id(): int {
		return $this->actor_id;
	}

	/**
	 * Returns the UTC timestamp string.
	 *
	 * @return string
	 */
	public function get_at_utc(): string {
		return $this->at_utc;
	}

	/**
	 * Returns the operation type.
	 *
	 * @return string
	 */
	public function get_op(): string {
		return $this->op;
	}
}
