<?php
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/../../../../' );
}

$evidence_dir = __DIR__;
$verification_json = file_get_contents( __DIR__ . '/../planning/currency-source-verification.json' );
$verification = json_decode( $verification_json, true );

$selection_date = $verification['selection_date'];
$sources = $verification['sources'];

$cache_dir = $evidence_dir . '/cache';
if ( ! is_dir( $cache_dir ) ) {
    mkdir( $cache_dir, 0777, true );
}

$downloads = [];
foreach ( $sources as $source ) {
    $filename = basename( parse_url( $source['url'], PHP_URL_PATH ) );
    $filepath = $cache_dir . '/' . $filename;
    
    if ( ! file_exists( $filepath ) ) {
        echo "Downloading {$source['url']}...\n";
        $content = file_get_contents( $source['url'] );
        if ( false === $content ) {
            fwrite( STDERR, "Failed to download {$source['url']}\n" );
            exit( 1 );
        }
        file_put_contents( $filepath, $content );
    } else {
        $content = file_get_contents( $filepath );
        if ( false === $content ) {
            fwrite( STDERR, "Failed to read {$filepath}\n" );
            exit( 1 );
        }
    }
    
    $hash = hash( 'sha256', $content );
    if ( $hash !== $source['sha256'] ) {
        fwrite( STDERR, "Hash mismatch for {$filename}. Expected {$source['sha256']}, got {$hash}\n" );
        exit( 1 );
    }
    
    $downloads[$filename] = $content;
}

$currency_data = json_decode( $downloads['currencyData.json'], true );
if ( json_last_error() !== JSON_ERROR_NONE ) { fwrite( STDERR, "JSON decode failed for currencyData.json\n" ); exit( 1 ); }
$currencies_en = json_decode( $downloads['currencies.json'], true );
if ( json_last_error() !== JSON_ERROR_NONE ) { fwrite( STDERR, "JSON decode failed for currencies.json\n" ); exit( 1 ); }
$license_text = $downloads['LICENSE'];

$regions = $currency_data['supplemental']['currencyData']['region'];
$fractions = $currency_data['supplemental']['currencyData']['fractions'];
$en_names = $currencies_en['main']['en']['numbers']['currencies'];

$selected_codes = [];

foreach ( $regions as $region => $currencies ) {
    foreach ( $currencies as $currency_entry ) {
        foreach ( $currency_entry as $code => $info ) {
            $tender = isset( $info['_tender'] ) ? $info['_tender'] : 'true';
            if ( $tender === 'false' ) {
                continue;
            }
            
            $from = isset( $info['_from'] ) ? $info['_from'] : '0000-00-00';
            $to = isset( $info['_to'] ) ? $info['_to'] : '9999-99-99';
            
            if ( $from <= $selection_date && $to >= $selection_date ) {
                $selected_codes[$code] = true;
            }
        }
    }
}

$codes = array_keys( $selected_codes );
sort( $codes );

if ( count( $codes ) !== $verification['selectable_count'] ) {
    fwrite( STDERR, "Count mismatch. Expected {$verification['selectable_count']}, got " . count( $codes ) . "\n" );
    exit( 1 );
}

$catalog_version = $verification['version'] . '-' . $selection_date;

$php_data = "<?php\n/**\n * Currency catalog data.\n *\n * @package MF\VeLog\n */\n\n";
$php_data .= "namespace MF\\VeLog\\Common\\Regional;\n\n";
$php_data .= "if ( ! defined( 'ABSPATH' ) ) {\n";
$php_data .= "    exit;\n";
$php_data .= "}\n\n";
$php_data .= "/**\n";
$php_data .= " * Generated by derive-catalog.php.\n";
$php_data .= " * Source: Unicode CLDR {$verification['version']} (snapshot {$selection_date})\n";
$php_data .= " *\n";
$php_data .= " * LICENSE:\n";
$lines = explode( "\n", $license_text );
foreach ( $lines as $line ) {
    $php_data .= " * " . rtrim( $line ) . "\n";
}
$php_data .= " */\n";
$php_data .= "class CurrencyCatalogData {\n\n";
$php_data .= "    /**\n";
$php_data .= "     * Gets the catalog.\n";
$php_data .= "     *\n";
$php_data .= "     * @return array\n";
$php_data .= "     */\n";
$php_data .= "    public static function get_catalog(): array {\n";
$php_data .= "        return [\n";

foreach ( $codes as $code ) {
    $name = isset( $en_names[$code]['displayName'] ) ? $en_names[$code]['displayName'] : $code;
    $symbol = isset( $en_names[$code]['symbol'] ) ? $en_names[$code]['symbol'] : $code;
    
    $digits = 2; // DEFAULT
    if ( isset( $fractions[$code]['_digits'] ) ) {
        $digits = (int) $fractions[$code]['_digits'];
    } elseif ( isset( $fractions['DEFAULT']['_digits'] ) ) {
        $digits = (int) $fractions['DEFAULT']['_digits'];
    }
    
    $name = addslashes( $name );
    $symbol = addslashes( $symbol );
    
    $php_data .= "            '{$code}' => [\n";
    $php_data .= "                'code' => '{$code}',\n";
    $php_data .= "                'name' => '{$name}',\n";
    $php_data .= "                'symbol' => '{$symbol}',\n";
    $php_data .= "                'scale' => {$digits},\n";
    $php_data .= "                'catalog_version' => '{$catalog_version}',\n";
    $php_data .= "            ],\n";
}

$php_data .= "        ];\n";
$php_data .= "    }\n";
$php_data .= "}\n";

$target_dir = __DIR__ . '/../../../../src/Common/Regional';
if ( ! is_dir( $target_dir ) ) {
    mkdir( $target_dir, 0777, true );
}
$written = file_put_contents( $target_dir . '/CurrencyCatalogData.php', $php_data );
if ( $written !== strlen( $php_data ) ) {
    fwrite( STDERR, "Failed to write full catalog data\n" );
    exit( 1 );
}

echo "Catalog generated successfully at src/Common/Regional/CurrencyCatalogData.php\n";
