// Independent review probes. Only owned temporary fixtures are mutated.
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const root=process.cwd(), out=path.join(root,'ai-document/evidence/WF-004/architect-round-2');
const {publishHandoff}=await import(path.join(root,'scripts/publish-handoff.mjs'));
const {validateHandoffMetadata}=await import(path.join(root,'scripts/handoff-protocol.mjs'));
const {ControllerState,pollCycle,startMonitor,acquireControllerLock,releaseControllerLock}=await import(path.join(root,'scripts/handoff-controller.mjs'));
const {dispatch}=await import(path.join(root,'scripts/agent-adapters/codex.mjs'));
const fixtures=[],results=[];
const put=(d,p,s)=>fs.writeFile(path.join(d,p),typeof s==='string'?s:JSON.stringify(s));
const record=(name,observed,expected)=>{const r={name,observed,expected};results.push(r);console.log(JSON.stringify(r));};
const task='ai-document/tasks/TEST-001-fixture.md';
const cfg={enabled:true,priorityTask:'TEST-001',adapters:{antigravity:{executable:'/stub',sessionId:'builder'},codex:{executable:'/stub',sessionId:'architect'}}};
const state=()=>Object.assign(new ControllerState(),{mode:'dispatch'});
async function fixture(){const d=await fs.mkdtemp(path.join(os.tmpdir(),'wf004-r2-'));fixtures.push(d);await fs.mkdir(path.join(d,'ai-document/tasks'),{recursive:true});await fs.mkdir(path.join(d,'.cache/handoff'),{recursive:true});await put(d,task,'# TEST-001: Fixture\n\n## Current handoff\n- Status: READY\n- Plan revision: 1\n- Latest round: 1\n- Next actor: Builder\n\n### Chat handoff prompt\n\n```text\nStatus: READY\nTest prompt.\n```\n');await put(d,'ai-document/implementation-checklist.md','# Checklist\n\n## Current focus\n\n- Task: TEST-001\n- Status: READY\n- Next actor: Builder\n');await put(d,'ai-document/README.md','TEST-001 READY; Builder.\n');await put(d,'ai-document/agent-roles.json',{schema_version:1,assignments:{codex:{role:'architect'},antigravity:{role:'builder'}}});await put(d,'ai-document/handoff-signal.json',{schema_version:1,handoff:null});return d;}
const opts=d=>({projectRoot:d,taskId:'TEST-001',taskFile:task,planRevision:1,round:1,taskStatus:'READY',intent:'work',fromRole:'architect',toRole:'builder',senderSessionId:'sender',prompt:'Status: READY\nTest prompt.',documentPaths:[task,'ai-document/implementation-checklist.md','ai-document/README.md']});
try {
 let d=await fixture();let p=await publishHandoff(opts(d));let n=0;await pollCycle(d,cfg,state(),{builder:{dispatch:async()=>{n++;return {success:true};}}});record('positive consistent fixture',{launches:n},'one launch');
 d=await fixture();await put(d,task,(await fs.readFile(path.join(d,task),'utf8')).replace('Plan revision: 1','Plan revision: 99').replace('Latest round: 1','Latest round: 99'));await put(d,'ai-document/implementation-checklist.md','# Checklist\n## Current focus\n- Task: TEST-001\n- Status: DONE\n- Next actor: User\n');await put(d,'ai-document/README.md','TEST-001 DONE; no work authorized.');p=await publishHandoff(opts(d));n=0;await pollCycle(d,cfg,state(),{builder:{dispatch:async()=>{n++;return {success:true};}}});record('revision round checklist README mismatch',{published:!!p.id,launches:n,validation:await validateHandoffMetadata(d,p.signal)},'reject and zero launches');
 d=await fixture();const first=await publishHandoff(opts(d));const second=await publishHandoff(opts(d));record('unacknowledged replacement',{first:first.id,second:second.id,replaced:true},'reject second, preserve first');
 d=await fixture();p=await publishHandoff(opts(d));const s=state();await pollCycle(d,cfg,s,{builder:{dispatch:async()=>({success:true})}});p.signal.handoff.round=42;await put(d,'ai-document/handoff-signal.json',p.signal);await pollCycle(d,cfg,s,{});record('same ID changed round',{errors:s.errors},'tamper error');
 d=await fixture();await publishHandoff(opts(d));const missing=state();await pollCycle(d,cfg,missing,{});n=0;await pollCycle(d,cfg,missing,{builder:{dispatch:async()=>{n++;return {success:true};}}});record('adapter repaired same process',{launchesAfterRepair:n,lastReceipt:missing.lastReceiptId,blocked:missing.blocked},'one launch after repair');
 d=await fixture();await publishHandoff(opts(d));const actualMap={codex:{dispatch:async()=>({success:true})},antigravity:{dispatch:async()=>({success:true})}};const mapState=state();await pollCycle(d,cfg,mapState,actualMap);record('dashboard adapter map uses client keys',{dispatchCount:mapState.dispatchCount,blocked:mapState.blocked},'one dispatch with injected production map');
 d=await fixture();await fs.cp(path.join(root,'scripts'),path.join(d,'scripts'),{recursive:true});const cli=spawnSync(process.execPath,[path.join(d,'scripts/validate-handoff.mjs'),'--task=ai-document/tasks/MISSING.md','--receipt='+randomUUID(),'--json'],{encoding:'utf8'});record('validator nonexistent task with empty signal',{exit:cli.status,stdout:cli.stdout},'nonzero missing task/receipt');await publishHandoff(opts(d));const validCli=spawnSync(process.execPath,[path.join(d,'scripts/validate-handoff.mjs'),'--task='+task,'--json'],{encoding:'utf8'});record('validator documented task path on valid receipt',{exit:validCli.status,stdout:validCli.stdout},'exit 0');
 d=await fixture();const h={id:randomUUID(),task_id:'TEST-001',task_file:task,task_status:'READY_FOR_REVIEW',intent:'work',from_role:'builder',plan_revision:1,round:1};const fake=path.join(d,'fake-cli');await fs.writeFile(fake,'#!'+process.execPath+'\n'+`const fs=require('node:fs');process.stdin.resume();process.stdin.on('end',()=>{const a=process.argv.slice(2);fs.writeFileSync(a[a.indexOf('-o')+1],JSON.stringify(${JSON.stringify({receipt_id:h.id,task_id:h.task_id,intake:'INVALID',outcome:'INVALID'})}));console.log('not-json');console.log(JSON.stringify({type:'thread.started',thread_id:'WRONG-SESSION'}));console.log(JSON.stringify({type:'turn.completed'}));});\n`,{mode:0o700});const r=await dispatch({projectRoot:d,config:{executable:fake,sessionId:'expected-session'},handoff:h,runId:randomUUID(),deadline:2000});record('Codex wrong thread malformed stream invalid result',{success:r.success,result:r.result,events:r.events},'failure');

 d=await fixture();await publishHandoff(opts(d));await put(d,'.cache/handoff/config.json',cfg);const lock=await acquireControllerLock(d);n=0;const locked=await startMonitor(d,{interval:100000,adapters:{builder:{dispatch:async()=>{n++;return {success:true};}}}});await locked.stop();await releaseControllerLock(lock);record('held controller lock',{launches:n,mode:locked.state.mode},'zero launches, observe');
 d=await fixture();await publishHandoff({...opts(d),parentRunId:randomUUID()});n=0;const parentState=state();await pollCycle(d,cfg,parentState,{builder:{dispatch:async()=>{n++;return {success:true};}}});record('unknown parent',{launches:n,blocked:parentState.blocked},'zero launches with blocker');
 d=await fixture();await publishHandoff(opts(d));await put(d,'.cache/handoff/ledger.json','{broken');let corruptError=null;try{await pollCycle(d,cfg,state(),{});}catch(e){corruptError=e.message;}record('corrupt JSON ledger',{error:corruptError},'explicit error, no reset');
 d=await fixture();await publishHandoff(opts(d));await put(d,'.cache/handoff/config.json',cfg);let notify,release;const begun=new Promise(r=>notify=r),pending=new Promise(r=>release=r);let returned=false;const starting=startMonitor(d,{interval:100000,adapters:{builder:{dispatch:async()=>{notify();await pending;return {success:true};}}}}).then(m=>{returned=true;return m;});await begun;record('monitor handle during initial active dispatch',{handleReturned:returned},'handle available to dashboard shutdown while initial dispatch runs');release();const runningMonitor=await starting;await runningMonitor.stop();
}finally{for(const d of fixtures)await fs.rm(d,{recursive:true,force:true});record('cleanup',{removed:fixtures.length},'all owned fixtures removed');await fs.writeFile(path.join(out,'probe-results.json'),JSON.stringify(results,null,2)+'\n');}
